name: fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - pytest=8.3.2
  - requests==2.24.0
  - fastapi=0.112.0
  - uvicorn=0.32.0
  - gunicorn=22.0.0
  - pip=23.2.1
  - pip:
      - wandb==0.18.3
      - hydra-joblib-launcher==1.1.2
      - databricks_cli==0.8.7
